### PR TITLE
Import previous event data#1073

### LINKED ISSUE #1073: Event Creation - Allow user to import data from other event when creating new event
When a user clicks "New Event" and is dropped into the event creation view they should be presented with a modal which gives them the option to import basic info from another event within their org. 

The user should be able to use a typeahead search field to find an event (using the same dropdown UI as the box office event list for the typeahead results) or can choose to skip the step and enter the empty event creation form

NOTE: If using just the same dropdown as the box office event selector with no typeahead makes this significantly easier to implement for now you can do that and order alphabetically by event name.

If they select the event and click "Import Settings" it should simply pre-fill the following fields with data:
- Venue
- Event type
- Show time
- Door time
- End time
- Age limit

Eventually we'll expand this feature to include ticket types and other options, but for now we just want to implement the quick solution to cut out a few steps in setting up an event

"Save time by importing event settings from a different event. This will import basic event information like Door Time, Show Time, End Time, Age Restrictions, and Venue. You can always make changes after importing."
image

### PR DESCRIPTION
**Pull request by Jasonvdb**
Closes #1073

### CODE REVIEW

**Comment by Krakaw** [comment]
As per description in https://github.com/big-neon/bn-web/issues/1073 the above are not required. @zmelamed let us know if you want those added into the clone.

**Comment by zmelamed** [comment]
> As per description in #1073 the above are not required. @zmelamed let us know if you want those added into the clone.

No we don't need those, for this round we're more focused on the more generalizable venue/event operations settings. QAing now

**Comment by zmelamed** [comment]
1. The list of events to choose from should show past and upcoming
2. Unable to scroll to the last item in the scroll area
3. Strange timezone issue I'm seeing:
I import an event in that's starting at 8:00PM CDT and the imported date/time show as 7:00PM CST... 
Event Being Cloned:
big_neon___concert_and_live_event_ticketing

Resulting Import:
big_neon___concert_and_live_event_ticketing

**Comment by Jasonvdb** [comment]
@zmelamed have fixed number 1. 
2 is a container issue, seeing what I can do there.
3 is a weird one, looking into that

**Pull request merged**
