### PR TITLE
Added DriftBot on CTA Click

### PR DESCRIPTION
**Pull request by zmelamed**

### CODE REVIEW

**Comment by Jasonvdb** [comment]
@Krakaw is it possible to easily inject an env var into a .html file for Drift?

**Comment by zmelamed** [comment]
Pretty positive we could only do that if we had a build script generating the page before deploy. Pretty sure I can lock it down by domain. Not all that concerned as it and other client side pixels/widgets will have their keys exposed through a simple view source no matter how we do it.

**Comment by Jasonvdb** [comment]
Ok then I'll merge and create an issue for later to add it to .env file and inject it.

**Comment by Krakaw** [comment]
We can write our own little webpack hook later on to inject vars.

**Pull request merged**
