### PR TITLE
On user refreshToken failure, clear localStorage

### PR DESCRIPTION
**Pull request by Krakaw**

### CODE REVIEW

**Comment by Jasonvdb** [comment]
Won't this remove tokens for any errors? Like if they get a network error temporarily they'll have to login again. What if you check for whatever status code is returned for an invalid token and only remove tokens on that

**Comment by zmelamed** [comment]
I pulled this down and I'm still receiving the same `Invalid token` error when I try and load

**Comment by zmelamed** [comment]
If I load directly in my browswer: `https://beta.bigneon.com/api/events/48ff9454-d56b-4dcb-b479-d34490506db4` there's no error
If I load directly in my browser through the proxy (which is what my local env is setup to do): `https://thingproxy.freeboard.io/fetch/https://beta.bigneon.com/api/events/48ff9454-d56b-4dcb-b479-d34490506db4` I get an error `{"message": "Internal server error"}`

Seems like an issue with the proxy?

**Comment by zmelamed** [comment]
So this has something to do with bn-api-node v0.3.20... forcing the web app to use 0.3.19 there is no issue

**Comment by Krakaw** [comment]
It is in 0.3.20, I know exactly what the problem is. I'll sort it out in the morning.

**Pull request closed without merging**
